# ################################
# Model: Classification with xvector
# Authors: Hwidong Na & Mirco Ravanelli
#          Script adapted by David Raby-Pepin 2021
# ################################

# Basic parameters
seed: 122
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Use 12 for V2 12 task and 35 for V2 35 task
number_of_commands: 3
output_folder: !ref results/xvect_v<number_of_commands>/<seed>
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
tensorboard_logs: !ref <output_folder>/logs
# noise_csv: /home/wangwei/work/speechbrain/recipes/lanso/results/aug.csv
noise_csv: /home/wangwei/work/speechbrain/recipes/lanso/results/wham_noise_tr_aug.csv
# noise_csv: /home/wangwei/work/corpus/kws/lanso/record/noise_aug/noise_record_aug.csv
# noise_csv: /home/wangwei/work/speechbrain/recipes/lanso/results/noise_train_office.csv
# noise_csv_add_reverb: /home/wangwei/work/speechbrain/recipes/lanso/results/youjie_keywords_001.csv

# Data files
data_folder: !PLACEHOLDER  # e.g. /path/to/GSC
train_annotation: !ref results/keyword2/save35/train.csv
valid_annotation: !ref results/keyword2/save35/dev.csv
test_annotation: !ref results/keyword2/record2/test.csv

# Folder to extract data augmentation files
rir_folder: !ref <rir_folder> # Change it if needed

# The train logger writes training statistics to a file, as well as stdout.
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

use_tensorboard: True
# Tensorboard logger (optional)
tensorboard_train_logger: !new:speechbrain.utils.train_logger.TensorboardLogger
    save_dir: !ref <tensorboard_logs>

# Percentage of files used for validation and test
validation_percentage: 10
testing_percentage: 10

# Percentage of unknown and silence examples
# (relative to total of known word samples) to include
percentage_unknown: 10 # Set this to 0 for the V2 35 task
percentage_silence: 10 # Set this to 0 for the V2 35 task

# Wether to use data augmentation
apply_data_augmentation: True
skip_prep: True
ckpt_interval_minutes: 3 # save checkpoint every N min

# Training parameters
number_of_epochs: 100
batch_size: 32
lr: 0.001
lr_final: 0.0001

sample_rate: 16000
shuffle: True


# Feature parameters
n_mels: 40
left_frames: 0
right_frames: 0
deltas: False
use_log1p: False

# Number of classes (i.e. different commands)
out_n_neurons: !ref <number_of_commands>  #includes core commands & auxiliary words

dataloader_options:
    batch_size: !ref <batch_size>
    shuffle: !ref <shuffle>
    num_workers: 32

# Functions
compute_features: !new:speechbrain.lobes.features.Fbank
    n_mels: !ref <n_mels>
    left_frames: !ref <left_frames>
    right_frames: !ref <right_frames>
    deltas: !ref <deltas>

embedding_model: !new:models.mdtc.MDTC
    stack_num: 3
    stack_size: 4
    in_channels: 40
    res_channels: 32
    kernel_size: 5
    causal: True

    # input_dim: !ref <n_mels>
    # output_size: !ref <out_n_neurons>
    # att_feature: 32

# classifier: !new:speechbrain.lobes.models.Xvector.Classifier
#     input_shape: [null, null, 512]
#     activation: !name:torch.nn.LeakyReLU
#     lin_blocks: 1
#     lin_neurons: 512
#     out_neurons: !ref <out_n_neurons>

softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

# Frequency domain SpecAugment
augment_spec: !new:speechbrain.lobes.augment.SpecAugment
    time_warp: False
    time_warp_window: 5
    time_warp_mode: bicubic
    freq_mask: True
    n_freq_mask: 2
    time_mask: True
    n_time_mask: 2
    replace_with_zero: False
    freq_mask_width: 10
    time_mask_width: 40

augment_wavedrop: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
    sample_rate: !ref <sample_rate>
    speeds: [100]

augment_speed: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
    sample_rate: !ref <sample_rate>
    speeds: [95, 100, 105]

add_rev: !new:speechbrain.lobes.augment.EnvCorrupt
    openrir_folder: !ref <rir_folder>
    openrir_max_noise_len: 1.5  # seconds
    reverb_prob: 1.0
    noise_prob: 0.0
    noise_snr_low: 0
    noise_snr_high: 15
    rir_scale_factor: 1.0

add_noise: !new:speechbrain.lobes.augment.EnvCorrupt
    openrir_folder: !ref <rir_folder>
    openrir_max_noise_len: 1.5  # seconds
    reverb_prob: 0.0
    noise_prob: 0.5
    noise_snr_low: 10
    noise_snr_high: 40
    rir_scale_factor: 1.0
    noise_csv: !ref <noise_csv>

add_rev_noise: !new:speechbrain.lobes.augment.EnvCorrupt
    openrir_folder: !ref <rir_folder>
    openrir_max_noise_len: 1.5  # seconds
    reverb_prob: 0.5
    noise_prob: 0.5
    noise_snr_low: -5
    noise_snr_high: 20
    rir_scale_factor: 1.0
    # noise_csv: !ref <noise_csv_add_reverb>


# Definition of the augmentation pipeline.
# If concat_augment = False, the augmentation techniques are applied
# in sequence. If concat_augment = True, all the augmented signals
# # are concatenated in a single big batch.
augment_pipeline: [
    !ref <augment_wavedrop>,
    !ref <augment_speed>,
    # !ref <add_rev>,
    !ref <add_noise>,
    # !ref <add_rev_noise>
]

# augment_pipeline: [
#     !ref <add_rev>,
#     !ref <add_noise>,
#     !ref <add_rev_noise>
# ]
concat_augment: True

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: sentence
    std_norm: False

modules:
    compute_features: !ref <compute_features>
    augment_wavedrop: !ref <augment_wavedrop>
    augment_speed: !ref <augment_speed>
    add_rev: !ref <add_rev>
    add_noise: !ref <add_noise>
    add_rev_noise: !ref <add_rev_noise>
    embedding_model: !ref <embedding_model>
    mean_var_norm: !ref <mean_var_norm>


# Cost + optimization
compute_cost: !name:speechbrain.nnet.losses.nll_loss
# compute_cost: !name:speechbrain.nnet.losses.mse_loss
compute_error: !name:speechbrain.nnet.losses.classification_error

opt_class: !name:torch.optim.Adam
    lr: !ref <lr>
    weight_decay: 0.000002

# opt_class: !name:torch.optim.Adadelta

# opt_class: !name:torch.optim.SGD
#     lr: !ref <lr>
#     momentum: 0.9
#     weight_decay: 0.000002

lr_annealing: !new:speechbrain.nnet.schedulers.LinearScheduler
    initial_value: !ref <lr>
    final_value: !ref <lr_final>
    epoch_count: !ref <number_of_epochs>

error_stats: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.classification_error
        reduction: batch

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        embedding_model: !ref <embedding_model>
        normalizer: !ref <mean_var_norm>
        counter: !ref <epoch_counter>

pretrained_path: /home/wangwei/work/speechbrain/recipes/lanso/results/xvect_v3/93196
# pretrained_path: /home/wangwei/work/speechbrain/recipes/lanso/results/xvect_v3/113
pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
    collect_in: !ref <pretrained_path>
    loadables:
        embedding_model: !ref <embedding_model>
    paths:
        embedding_model: !ref <pretrained_path>/embedding_model.ckpt